build:

default:
  - 'test'

dependencies:
  - 'clean:pmd'
  - 'curl:pmd'
  - 'curl:commonsio'
  - 'exec:unzip'
  - 'exec:patchpmd'
  - 'curl:pmdjs'

dev:

lint:
  - 'jshint'

test:
  - 'jshint'
  - 'nodeunit'
